FROM python:3.8-slim-buster

MAINTAINER vladskvortsov

COPY bot.py requirements.txt /telegram_bot/ 

WORKDIR /telegram_bot 

RUN pip3 install -r requirements.txt 

CMD [ "python3", "./bot.py" ]

EXPOSE 5000

