
service: telegram-bot-serverless-v12

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-2
  environment:
    TELEGRAM_TOKEN: 



functions:
  post:
    handler: handler.hello
    events:
      - http:
          path: my-custom-url
          method: post
          cors: true


