name: Deploy Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: zip lambda.zip /lambda-function/lambda_function.py
      - uses: yvesgurcan/deploy-lambda-function@master
        with:
          package: lambda.zip
          function-name: 'telegram_bot'
          AWS_REGION: 'eu-west-2'
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}


#          requirements_txt: 'requirements.txt'    
#        env:
#          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN}}










