name: Pull to dockerhub and deploy to server via ssh

on:
  push:
    branches:
      - "master"

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./telebot/
          file: ./telebot/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/telegram_bot:latest

  deploy_to_remote_server:
    runs-on: ubuntu-latest
    needs: build_docker_image
    steps:
      - name: Deploy docker image to remote server via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |

            sudo docker login docker.io -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }
            sudo docker run -d -p 5000:5000 vladskvortsov/telegram_bot:latest

